#ifndef DEFINICOES_H_
#define DEFINICOES_H_

#define FUNCTION_COD_SEND 0x16
#define FUNCTION_COD_RESQUEST 0x23
#define SUB_COD_SEND_INT 0xB1
#define SUB_COD_SEND_FLOAT 0xB2
#define SUB_COD_SEND_STRING 0xB3
#define SUB_COD_REQUEST_INT 0xA1
#define SUB_COD_REQUEST_FLOAT 0xA2
#define SUB_COD_REQUEST_STRING 0xA3

#endif 
